### ISSUE TITLE
Problem facing in CCS during the compilation by using your project 

### ISSUE THREAD

**Issue by Keerthivasan-coder** [Dasch0/ei-ti154-remote-monitor#2] opened 2022-03-28 08:49 UTC
Hi @Dasch0 
I have imported your project in my code composer studio and tried to bulid the project by following the given procedure.
During the compilation, I've been facing the following errors in gmake, makefiles.
Kindly assist me regarding the project.

Description
gmake: *** [../src/sysbios/rom_sysbios.aem4f] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake: *** [build-1322531727] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake: *** [E:/SS/ei-ti154-remote-monitor-main/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/src/makefile.libs:57: E:/SS/ei-ti154-remote-monitor-main/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/src/sysbios/rom_sysbios.aem4f] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake: Target 'all' not remade because of errors.	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [build-1322531727-inproc] Error 1	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [m3_Hwi_asm_switch.obj] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [m3_Hwi_asm.obj] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [m3_IntrinsicsSupport_asm.obj] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [m3_TaskSupport_asm.obj] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [makefile:60: rom_sysbios.obj] Error 127	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [rom_sysbios.obj] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: Target 'all' not remade because of errors.	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
recipe for target '../src/sysbios/rom_sysbios.aem4f' failed	makefile.libs	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/src	line 56	C/C++ Problem
recipe for target 'build-1322531727' failed	subdir_rules.mk	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 9	C/C++ Problem
recipe for target 'build-1322531727-inproc' failed	subdir_rules.mk	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 12	C/C++ Problem
recipe for target 'm3_Hwi_asm_switch.obj' failed	makefile	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 45	C/C++ Problem
recipe for target 'm3_Hwi_asm.obj' failed	makefile	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 41	C/C++ Problem
recipe for target 'm3_IntrinsicsSupport_asm.obj' failed	makefile	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 49	C/C++ Problem
recipe for target 'm3_TaskSupport_asm.obj' failed	makefile	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 53	C/C++ Problem
recipe for target 'rom_sysbios.obj' failed	makefile	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 58	C/C++ Problem
xdc.cfg.SourceDir : Build of generated source libraries failed: exit status = 2:	.xdchelp	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang	line 211	C/C++ Problem
xdctools_3_62_01_16_core\gmake.exe: *** [package/cfg/app_pem4f.xdl] Deleting file 'package/cfg/app_pem4f.c'	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
xdctools_3_62_01_16_core\gmake.exe: *** [package/cfg/app_pem4f.xdl] Deleting file 'package/cfg/app_pem4f.h'	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
xdctools_3_62_01_16_core\gmake.exe: *** Deleting file 'package/cfg/app_pem4f.xdl'	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem

**Comment by Dasch0** [comment] 2022-03-31 23:36
Hi @Keerthivasan-coder,

I reproduced the issue, and after some debuggging, it turns out to be due to improperly exporting the project - specific SDK and sysconfig versions were not properly defined and this caused issues when a fresh Code Composer installation attempted to import the projects.

Additionally, I found a separate issue with the latest code composer version when testing the fix. It looks like imported projects require the [project].syscfg file to be opened and saved in order to perform proper code and makefile generation. I was not able to get code composer to export projects that worked properly without performing this step, so I've added the proper instructions to the README in the above commit.

Hopefully this will resolve your build issues. Please test this, following the new instructions in the README, and confirm the issue is resolved.

**Comment by Keerthivasan-coder** [comment] 2022-04-02 05:50
Hi @Dasch0 
Thank you for the support.. 
I implemented every steps you have mentioned and exported your project properly..
The error has been resolved in ei_collector and [ Collector ] . out file generated , 
But still facing an error and warning on ei_sensor project, 
Description 
gmake[1]: *** [ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang.out] Error 1	path : ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	
gmake: *** [all] Error 2	path : ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 
recipe for target 'ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang.out' failed	makefile	
Path : **### /ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release**	
recipe for target 'all' failed	makefile 	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	

Warning : LOW_OPTIMIZATION_ENTER
unknown attribute 'optimize' ignored [-Wunknown-attributes]	arm_biquad_cascade_df2T_f16.c	 
Path : ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions	

How do we resolve this??

**Comment by Dasch0** [comment] 2022-04-06 02:27
Hey @Keerthivasan-coder,

I'm not sure exactly what the issue is for this part, unfortunately the core error message there isn't giving up the details on what is actually happening.

I can confirm that I am seeing the `LOW_OPTIMIZATION_ENTER` warning even on successful builds, so I don't think this is the issue.

Would you provide the contents of the release folder and check if there are any other details in the raw console log output? Maybe there's a linker error in the mix that isn't displaying properly in the ccs ui.

One other thing worth syncing up between our builds, what platform (OS) and CCS version are you running off of? I'm successfully building from mac + CCS1100, and in the past I successfully built from CCS1030. Unlikely to be the root cause but good to check, I had an issue report today that our linker file for some other CCS + EI projects was breaking the command length limit on windows, but I wasn't seeing it on mac/linux - if you are on windows, I can try building on a test machine.

**Comment by Dasch0** [comment] 2022-04-06 06:30
For a different project with TI, we also happened to just publish a first draft of a generic integration guide for code composer projects here:
https://github.com/edgeimpulse/ei-ti-code-composer-examples

Could you walk through the main readme with a ticlang based example as a starting point? I'd be curious to see if you get the same errors as in this repo.

**Comment by Keerthivasan-coder** [comment] 2022-04-08 10:37
Hey David,
Sorry for not getting back to you sooner..

I've attached here the project that I'm currently working with and also
content of release folder screenshot is attached below..
 ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang.zip
<https://drive.google.com/file/d/1NVjO0foIsshDrDSdfKKyTHMs6zb4aKIi/view?usp=drive_web>

[image: image.png] <https://drive.google.com/file/d/1qpD-wp5JUUC3ZG8AURidBLurrRThlLAi/view?usp=sharing>

I have no idea why the error is produced on that invoking arm linker .. and
maybe you're right the linker error in the mix that isn't displaying
properly in the ccs ui.
I will try building the project with your integration guide, it would be curious to see if it works and generate .out file.
Kindly try building the project on a test windows machine and update me if we both are on same page.

I'm using ,
*Windows 10 Pro OS.*

*CCS - V11.1.0.*

*SimpleLink CC13xx/CC26xx SDK - v5.10.0.48.*

*Ti Arm Clang - 1.3.0 STS Compiler.*

*Sysconfig - 1.11.0.*

*XDCtools - 3.62.0.08_Core ( Same as mentioned in your project )..*


*Thank you for your time and patience.*

**Comment by Keerthivasan-coder** [comment] 2022-04-14 07:19
Hey @Dasch0,

Good day!

Thanks for the integration guide,

After going through the integration, I built a project using a TI CLANG-based example (Pin Interrupt) with your ball bearing Fault detection model...
The root cause as you said "The filename or extension is too long" same errors you mentioned in the repo.
Console error attachment:
(https://drive.google.com/file/d/1lWuxwhshrDaQE9LLHm7W7AAPkYneSYP9/view?usp=sharing)

I am not able to understand why the issue is happening exactly...
Could you please help me understand how to sort this out?

I will attempt to build the project in a Linux system after setting up the necessary environments for Linux.

**Comment by Dasch0** [comment] 2022-04-20 16:54
Hi Keerthivasan,

Copying this to cross link the forum thread and repo issues, but a workaround for the path issue is now available at:

https://github.com/edgeimpulse/ei-ti-code-composer-examples/issues/1#issuecomment-1104174427

I will close the issue here and follow up with a more robust fix in that repo. Long term this repository is likely going to be deprecated in favor of moving this project into `ei-ti-code-composer-examples`

**Closed as completed by Dasch0** 2022-04-20 16:54 UTC
